# Generated by Django 6.1.1 on 2026-09-14 17:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Tên phòng chỉ được chứa số')], verbose_name='Tên phòng')),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tầng')),
                ('area', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Diện tích (m²)')),
                ('max_occupancy', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số người tối đa')),
                ('amenities', models.TextField(blank=True, default='[]', verbose_name='Tiện nghi')),
                ('base_rent', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá thuê (đ/tháng)')),
                ('electricity_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá điện (đ/kWh)')),
                ('water_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá nước (đ/m³)')),
                ('trash_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Phí rác (đ/tháng)')),
                ('internet_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Phí internet (đ/tháng)')),
                ('current_electricity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Chỉ số điện hiện tại (kWh)')),
                ('current_water', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Chỉ số nước hiện tại (khối)')),
                ('status', models.CharField(choices=[('trong', 'Trống'), ('dang_thue', 'Đang thuê'), ('da_coc', 'Đã cọc'), ('sua_chua', 'Sửa chữa')], default='trong', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL, verbose_name='Chủ trọ')),
            ],
            options={
                'verbose_name': 'Phòng trọ',
                'verbose_name_plural': 'Danh sách phòng',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in_date', models.DateField(verbose_name='Ngày nhận phòng')),
                ('lease_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Thời hạn thuê (tháng)')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tiền cọc (đ)')),
                ('contract_image', models.ImageField(blank=True, null=True, upload_to='contracts/', verbose_name='Ảnh hợp đồng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_assignment', to='rooms.room', verbose_name='Phòng')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Người thuê')),
            ],
            options={
                'verbose_name': 'Thông tin người thuê',
                'verbose_name_plural': 'Thông tin người thuê',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField(verbose_name='Kỳ thanh toán (tháng)')),
                ('old_electricity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Chỉ số điện cũ (kWh)')),
                ('new_electricity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Chỉ số điện mới (kWh)')),
                ('old_water', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Chỉ số nước cũ (khối)')),
                ('new_water', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Chỉ số nước mới (khối)')),
                ('base_rent', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tiền phòng')),
                ('electricity_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Đơn giá điện')),
                ('water_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Đơn giá nước')),
                ('trash_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Phí rác')),
                ('internet_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Phí internet')),
                ('extra_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Phụ phí')),
                ('extra_fee_reason', models.TextField(blank=True, verbose_name='Lý do phụ phí')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Tổng cộng thanh toán (đ)')),
                ('status', models.CharField(choices=[('nhap', 'Nháp'), ('chua_tt', 'Chưa thanh toán')], default='nhap', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='rooms.room', verbose_name='Phòng')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'verbose_name_plural': 'Danh sách hóa đơn',
                'ordering': ['-billing_month'],
                'unique_together': {('room', 'billing_month')},
            },
        ),
    ]
